### ISSUE TITLE
Bug: Large GF Store Download Interruptions / Using a self- downloaded GF store

### ISSUE THREAD

**Issue by axelwang** [pyrocko/pyrocko#325]
Hey,
  I downloaded a rather huge (~50 GB) GF store from Green's Mill using a 3rd party downloader. The "Fomosto download" option would not work for this one because the internet connection is never uninterrupted at all during this long download and once it's slightly interrupted the download fails, so I am never able to complete it. 
  My question now is, how can I somehow change the code so that it knows where to find this self- downloaded store? I changed the 'store_id' properly and pointed my 'store_superdirs' to the approporiate directory where I have all my GF stores stored. With this setup, the ones downloaded using 'Fomosto download' or created using 'Fomosto build' can alwasy be found, but this self- downloaded one could not be found. I am guessing there are some additional paths need to be added, but I couldn't find where. 
My error message is:

```
Traceback (most recent call last):
  File "gf_forward_qssp.py", line 48, in <module>
    response = engine.process(source_dc, targets)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/seismosizer.py", line 2979, in process
    self.get_store(store_id)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/seismosizer.py", line 2756, in get_store
    store_dir = self.get_store_dir(store_id)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/seismosizer.py", line 2714, in get_store_dir
    raise NoSuchStore(store_id)
pyrocko.gf.seismosizer.NoSuchStore: no GF store with id "global_2s" found.
```

Please help! Thanks!

**Comment by hvasbath** [comment]
This should be working without problems. Please double check your paths, that the store is in your superpath, that the store directory name is according to your store_id and that the store_id is properly defined in the store_directory/config

**Comment by axelwang** [comment]
Hey,
  Thank you so much for your timely reply.

  I checked all of the things that you mentioned but the code still doesn't work.

  I am trying to use the 'global_2s' store.

1.  Store is located at: 
`axelwang$ ls
Synthetics         gf_forward_qssp.py global_20s_shallow global_2s
axelwang$ pwd
/Users/axelwang/Research/pyrocko-master/Synthetics
`

Super directory changed to: 
`engine = LocalEngine(store_superdirs=['/Users/axelwang/Research/pyrocko-master/Synthetics'])`

2. 
store_id, as shown above is 'global_2s'
In the synthetics code, I have: 
`# The store we are going extract data from:
store_id ='global_2s'`

3.
 In the config file, I have
`--- !pyrocko.gf.meta.ConfigTypeA
id: global_2s`


  I think these are all the things that you pointed out for me to check. I am not sure what other things might be included when you say "double check your paths". I am pretty new to python so please pardon me. If there are other things that more experienced user would change just from common sense, I wouldn't know these. 

  Thanks,
  Axel

**Comment by axelwang** [comment]
Also, I tried to move one of my self- created GF store, using 'fomosto build', to a different directory, and by changing the store_id and the super directory I am still able to find this GF store and use it. Really I think the difference is when I use 'Fomosto build' or 'Fomosto download' some paths are added somewhere so that changing the super directory and the store_id would be enough to find it. This is not the case apparently for this self- downloaded store whose introduction to my local machine did not involve using 'Fomosto'.

**Comment by hvasbath** [comment]
Sure it should work without problems.
What is the directory name of that store in your superdir?

**Comment by axelwang** [comment]
Hey,
  The store is located at, as shown,
`/Users/axelwang/Research/pyrocko-master/Synthetics`

  And the super directory path has been changed to
`engine = LocalEngine(store_superdirs=['/Users/axelwang/Research/pyrocko-master/Synthetics'])`

  I suppose this is the only place that I need to change for superdir? 

  Thanks!

**Comment by miili** [comment]
The name of the store's directory has to match the name in the config. It the store in
`/Users/axelwang/Research/pyrocko-master/Synthetics/global_2s`?

**Comment by axelwang** [comment]
Hey,
  I found the problem! 

  When I downloaded the store myself, somehow a '.txt' was appended to the 'config' file. After I removed that now everything works! 

  Thanks,
  Axel

**Comment by miili** [comment]
Excellent!
